import { DEFAULT_CHARACTER_ID, DEFAULT_REGION_ID } from "../config.js";
import { DEFAULT_SAFE_AREA_ID } from "../data/safeAreas.js";

export function createAdventureRuntimeState({
  regionDefinitions,
  characterDefinitions
}) {
  return {
    run: 0,
    selectedRegionId: DEFAULT_REGION_ID,
    selectedHeroId: DEFAULT_CHARACTER_ID,
    selectedRegion: regionDefinitions[DEFAULT_REGION_ID].name,
    selectedHero: characterDefinitions[DEFAULT_CHARACTER_ID].name,
    activeRouteId: null,
    routeEncounterIndex: 0,
    encounterIndex: 0,
    turn: 0,
    hero: null,
    enemies: [],
    targetEnemyId: null,
    selectedBoss: null,
    phase: "camp",
    awaitingBlessing: false,
    ended: false,
    defeatedEnemies: 0,
    defeatedBoss: false,
    deathCause: null,
    lastRunSummary: null,
    runStats: null,
    runPreparation: null,
    beachSegmentCompleted: false,
    coastSegmentCheckpoint: null,
    blessingInstances: [],
    blessingInstanceSequence: 0,
    campSelection: null,
    canRest: false,
    hasRested: false,
    ambushAdvantage: false,
    pendingThreat: null,
    blessingContext: "normal",
    blessingPoolOverrideId: null,
    blessingInputLocked: false,
    battleSource: "main",
    battleEncounterType: null,
    specialDuelContext: null,
    eventSchedule: null,
    eventContext: null,
    runEventRecords: [],
    eventInputLocked: false,
    adventureProgressLocked: false,
    eventTransitionToken: 0,
    debugBuildRun: false,
    storyTimer: null,
    routeEndingContext: null,
    runOriginSafeAreaId: null,
    pendingAnpingArrival: false,
    anpingArrivalContext: null,
    anpingArrivalInputLocked: false,
    anpingArrivalTimerIds: [],
    runResultRecorded: false,
    pendingAchievementUnlocks: [],
    activeAchievementToastId: null,
    achievementToastTimer: null,
    log: []
  };
}

export function createUiState() {
  return {
    navigationContext: "menu",
    regionView: "list",
    characterView: "list",
    characterDetailId: DEFAULT_CHARACTER_ID,
    equipmentPreviewWeaponId: null,
    equipmentNotice: "",
    equipmentNoticeType: "status",
    characterSkillSelectedId: null,
    characterSkillSearchQuery: "",
    characterSkillTypeFilter: "all",
    characterSkillStageFilter: "all",
    equipmentSearchQuery: "",
    equipmentCategoryFilter: "all",
    equipmentSortMode: "rarity",
    statisticsView: "overview",
    statisticsCharacterId: DEFAULT_CHARACTER_ID,
    statisticsRegionId: DEFAULT_REGION_ID,
    storageSortMode: "rarity",
    storageSortDirection: "desc",
    storageSearchQuery: "",
    storageRarityFilter: "all",
    storageSelectedMaterialId: null,
    storageUsageFilter: "all",
    storageExpandedUsageIds: new Set(),
    achievementFilter: "all",
    achievementSelectedId: null,
    achievementNewIds: new Set(),
    achievementDetailOpen: false,
    safeAreaId: DEFAULT_SAFE_AREA_ID,
    facilityView: "list",
    blacksmithReturnView: "list",
    blacksmithReturnNpcId: null,
    guildReturnNpcId: null,
    selectedPreparationId: null,
    enhancedPreparationId: null,
    preparationEnhancementRevealId: null,
    preparationDetailId: null,
    preparationDetailExpanded: false,
    runStartNotice: "",
    runStartLocked: false
  };
}
